### ISSUE TITLE
Hit and Crit chance show as zero

### ISSUE THREAD

**Issue by krautchanpro** [Otari98/BetterCharacterStats#1]
My hit and crit chance show as zero, changing to cat/bear form have the same issue:

![Screenshot 2024-10-09 030918](https://github.com/user-attachments/assets/f64a844c-1a7c-438e-879b-fe086f49b205)

**Comment by krautchanpro** [comment]
Interesting, the version here has the same issue:
https://github.com/pepopo978/BetterCharacterStats

**Comment by Otari98** [comment]
shows correct values for me 
![изображение](https://github.com/user-attachments/assets/a852c9f5-3cd7-451c-91fe-86f203fb7540)

**Comment by Otari98** [comment]
Found the reason, fixed via 96dc7a49bb808d153aa64d301d04fbc06e046066
