### ISSUE TITLE
Additonal problem comes: head/legs enchant counted twice

### ISSUE THREAD

**Issue by Szwedowski** [Otari98/BetterCharacterStats#10]
Sorry, I hurried
Looks like now +12 head/leg enchant counted twice for SPD and Healing: 68 base healing on legs + 12 + 12 = 92
Ironclad talant disabled
![image](https://github.com/user-attachments/assets/7ac510d5-d631-4887-a057-795907869203)
![image](https://github.com/user-attachments/assets/84abe954-aac7-4b7b-8819-7dce0996f184)

P.S. [Enchanted Armor Kit](https://database.turtle-wow.org/?item=61183) counted correctly

**Comment by Otari98** [comment]
should be fixed now 46b42e8e27728b670e153f984044de4efcc73847
also removed ranged tab from druids, paladins and shamans
healing tooltip will show how much Ironclad contributes to healing power

**Comment by Szwedowski** [comment]
Spell power and Healing power looks corectly for both my Holy and Protection specs
