### ISSUE TITLE
Healing/Spell Power values aren't updating

### ISSUE THREAD

**Issue by h4zm1** [Otari98/BetterCharacterStats#11]
Am a priest with Spiritual Guidance talent
![image](https://github.com/user-attachments/assets/99b60a84-9d8e-46bb-8d0d-3fa07c99c887)
I just noticed that buffing myself with spirit buffs like 
![image](https://github.com/user-attachments/assets/7d98e129-7010-4d5c-88ed-e7bb0c890e08)
![image](https://github.com/user-attachments/assets/0c0d85f3-a682-44a0-98db-f9cf00c3ad6b)
Doesn't change the values of healing power nor spell power
![image](https://github.com/user-attachments/assets/95ebe5e7-72f6-4e29-b0dd-ef6c2c16b0fa)
But picking something else from the drop list
![image](https://github.com/user-attachments/assets/32d3de09-846d-4b2d-a8ec-81877fcefcdc)
And then go back to "Spell" I find the healing and spell power values updated/changed
![image](https://github.com/user-attachments/assets/36ea7280-4d23-4808-88ef-8d0faa7eb127)
Reloging also makes the values update too, but they never update when I get a spirit buff, what does update tho is the Mana regen value, which seems like it's working fine, unlike the healing and spell power.

**Comment by Otari98** [comment]
Thanks for report, i will look into it.

**Comment by Otari98** [comment]
f0d7908cdc1e931a9ec67ea0f88e0d288052af49 Should be fixed now, let me know if its not still.

**Comment by h4zm1** [comment]
Works good now, thanks for the fast fix
