### ISSUE TITLE
Avoidance formula

### ISSUE THREAD

**Issue by Szwedowski** [Otari98/BetterCharacterStats#2]
Hello.
I saw that you added new field into Defenses table - Avoidance.
From code it calculated as text:SetText(format("%.2f%%", (GetBlockChance() + GetParryChance() + GetDodgeChance())))
But this not correctly, also miss chance should added.
I don't know the exact formula of miss chance, but this is it : base miss chance  + 0,04 * (Defence - 300).

I added some screenshots of gear planner Wowhead and Sixtyupgrades (Classic versions for 60 lvl character) for Paladin in the same gear.
![image](https://github.com/user-attachments/assets/6fb9d283-8dac-4ffa-bc77-f85b0fdaefba)
![image](https://github.com/user-attachments/assets/4c618940-e1ff-449b-8d94-cc5fff2ba9d2)
![image](https://github.com/user-attachments/assets/4d7a63f4-9d45-480d-823f-2ceacc4c1bee)

**Comment by Szwedowski** [comment]
I also found this info about miss change
https://github.com/magey/classic-warrior/wiki/Attack-table#miss

**Comment by Otari98** [comment]
I will look into it, thank you

**Comment by Otari98** [comment]
Fixed in the latest commit adeacc0530f1c92f0dd1594b91b56f69b0b1005f
Thank you for your report

**Comment by Szwedowski** [comment]
One small comment:  the avoidance cap is 102.4%
```
	if total > 100 then total = 100 end
	if total < 0 then total = 0 end
```

**Comment by Otari98** [comment]
How can you avoid more than 100% of something?

**Comment by Szwedowski** [comment]
100% avoidance is cap, when you attacked by mob of the same lvl as you.
The extra 2.4% is come from fighting with bosses who has 63 lvl.
So you need to reach 102,4% avoidance to be uncritable by raid boss.

**Comment by Otari98** [comment]
All stats in this addon calculated assuming you are fighting target of your level
