### ISSUE TITLE
Inner fire spell damage

### ISSUE THREAD

**Issue by tiffanyplus** [Otari98/BetterCharacterStats#4]
Inner fire SP increase doesn't show up on the spell power increase nor the 15/30% increase from the talent

**Comment by Otari98** [comment]
if you could provide more info on what tooltip on buff say it would help alot

**Comment by grynold** [comment]
"Increases armor by 1395. Increased damage dony by magical spells and effects by 73."

Thats with 1/2 point spent in the talent. 
Increases the effect of your Inner Fire spell by 15%. 
Next rank: Increases the effect of your Inner Fire spell by 30%.

**Comment by Szwedowski** [comment]
On new versions from Today +healing didn't added fron Ironclad talent. Yesterday worked

**Comment by Otari98** [comment]
Should be fixed in the latest version, closing this issue
