### ISSUE TITLE
Stats from enchantments on rings or necklaces are not added

### ISSUE THREAD

**Issue by SeguisDumble** [Otari98/BetterCharacterStats#5]
The new jewelcrafting profession has a few enchants for necklaces and rings, the stats from these enchants are not considered by the addon.
Thanks for all your work!

**Comment by Otari98** [comment]
Be more specific, screenshot item with enchant if possible

**Comment by SeguisDumble** [comment]
Ok, I test it again. Intelect enchant seems to work but healing enchant no. I can't create the spell power one yet.

Some screenshots with healing enchant

healing without a ring:
![image](https://github.com/user-attachments/assets/c6a09d46-faf2-4e03-99a6-f1204c5c51f9) 

So, if I equip this ring (with a total of 63 healing):
![image](https://github.com/user-attachments/assets/da75aa80-7ef2-4853-9c97-0dcc32cc98a9)
I should have 1113 healing power, but instead, I get:
![image](https://github.com/user-attachments/assets/ab7c0139-6631-48c8-adb6-0041d54aba8c)

So the 12 healing from the enchant are not getting added. I will try to gather more information about the other enchants

**Comment by Otari98** [comment]
Healing enchant should work, download the latest version

**Comment by Brinelb** [comment]
Hey. The characteristics from are not displayed https://www.wowhead.com/classic/item=20748/brilliant-mana-oil

**Comment by Otari98** [comment]
Thank you for your report, fixed via 9f561c6c94f1184132d2ecdc407aab74bc38f18b

**Comment by Brinelb** [comment]
Thx man, High Elf Hunter, does not display Ranged Crit Chance
![01](https://github.com/user-attachments/assets/7b339fd5-eb66-4235-a043-67f415920ea9)

**Comment by Otari98** [comment]
> Thx man, High Elf Hunter, does not display Ranged Crit Chance ![01](https://private-user-images.githubusercontent.com/187788455/384585590-7b339fd5-eb66-4235-a043-67f415920ea9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDcwNDEsIm5iZiI6MTczMTE0Njc0MSwicGF0aCI6Ii8xODc3ODg0NTUvMzg0NTg1NTkwLTdiMzM5ZmQ1LWViNjYtNDIzNS1hMDQzLTY3ZjQxNTkyMGVhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxMDA1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjlhMDg4Nzg0MzA2YmYyNDhiNzZhYTQ3YzA4NDg1MWUzNzQxNDkzNWM3NjYzNTQ3OTg1MjBiODM3MjY3ZmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ti5plY7MoDo1EGgmRkPP2qws7McbJ3jQWBIE2v9IzZ4)

Ranged crit calculation takes into account skill, but since the last patch some weapon skills are missing from the client due to a bug.
Made a temporary fix, but know that it will be inaccurate below maximum skill.

**Comment by Brinelb** [comment]
thank you =)
