### ISSUE TITLE
Amount of healing power changed

### ISSUE THREAD

**Issue by Szwedowski** [Otari98/BetterCharacterStats#7]
I am holy paladin, and have Ironclad talent.
On version from Nov 6, 2024 https://github.com/Otari98/BetterCharacterStats/tree/72129a1d656316f6933597eb77f79b7ff8ea41a7
I have 1120 healing power unbuffed. 
That amount looks correct: 987 healing power from gear + ((6788 armor from items - 138 armor from agility)  * 0,02)

But on current version addon displayed only 1096 healing power for me.
![image](https://github.com/user-attachments/assets/e314b0b5-7b12-4349-914e-2660b4fd7bff)

**Comment by Szwedowski** [comment]
![image](https://github.com/user-attachments/assets/58a2b13a-4f4a-4c76-9686-f2e80a7562a8)

**Comment by Otari98** [comment]
Ok, get new version, if its not fixed now let me know

**Comment by Szwedowski** [comment]
Now healing power calculated correctly. Thank you
