### ISSUE TITLE
Spell power from enchant isn't count

### ISSUE THREAD

**Issue by Szwedowski** [Otari98/BetterCharacterStats#9]
In version from Nov 16, 2024
https://github.com/Otari98/BetterCharacterStats/tree/87aad90e2c77a4217423ce7cc21aff79393b4dad
was broken calculation of +30 Spell power from weapon enchant
![image](https://github.com/user-attachments/assets/19bd896f-6700-488f-828f-41b179f1b73b)

**Comment by Otari98** [comment]
It got lost during refactoring, should be fixed now, thank you for a clean report again.

**Comment by Szwedowski** [comment]
Was rechecked in Turtle wow
* case 1 - Flash of Light(Rank1) with 1 item: sword 40 sp + enchant 30 sp = healing amount 98-107
* case 2 - Flash of Light(Rank1) with 1 item: belt 40 healing power = healing amount 84-93

**Comment by Szwedowski** [comment]
Additional test was executed for [Brilliant Wizard Oil](https://database.turtle-wow.org/?item=20749)
Increases spell damage by up to 36 and increases Spell Critical chance by 1%

    case 1 - Flash of Light(Rank1) without items at all = healing amount 67-77
    case 2 - Flash of Light(Rank1) with 1 item: white mace with applied Brilliant Wizard Oil = healing amount 82-92

So, Brilliant Wizard Oil also add Healing power

**Comment by Otari98** [comment]
does bracer spell damage enchant also add healing?

**Comment by Szwedowski** [comment]
In same time Greater Arcane Elixir (Increases spell damage by up to 35 ) isn't add Healling power

**Comment by Otari98** [comment]
hopefully fixed f8157857e7a082972a28b78d16997a9e6cfd8a9c

**Comment by Szwedowski** [comment]
Woks corectly now

**Comment by Szwedowski** [comment]
Sorry, I hurried
Looks like now +12 head/leg enchant counted twice : 68 base healing on legs + 12 + 12 = 92
![image](https://github.com/user-attachments/assets/7ac510d5-d631-4887-a057-795907869203)
![image](https://github.com/user-attachments/assets/84abe954-aac7-4b7b-8819-7dce0996f184)
